language: elixir
elixir:
- 1.3.4
otp_release:
- 19
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database elixir_lightning_talks_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: FrM1+TzMFmmmISbdNS3OEwNvkIBPjM0VlqqbqsquW+nsDFIjo6pa+4G1ONeBbDLrpiyIgfbd9zQ9UZaDfY6pFXUnY7mkCTjnqxlZLci1+tGqvDMM/wpa/7HDsYefZdzcGz1B23FHaODRcadHFrwgHG+0vY4VFXtJTD1Tz6b7JoLPPMKI0zVyNAzQXwqmVDCNyVaYWKBxpqGprZFN3reWz+EUhESHATyAgpzwsIKcK7bhxHaTcAKlfdZ6YfFf6TBro6rV7eAgpMgH7OvIgoVTbBEe0eZZVcVmHncNxxk1N16NyqVe8YjSuXqV3rcM6Fy/E780uX5uscSzM+YZ4Yo1tHEjw27M0pFo7TK1skTBtBjGNTicsi1gJND/HZkG8XH/svKIAzeJ725J8U89TDE3Ze8m1FAYGRTrODOcABtnIH28f+RFfs8ElBhwHV8aMWRurswOy+i2bQIkAygEb0amm2ggy12wDsF3R2Pwjn9wqp6qQNvIMr4RdRwRkI78Iaw354x5ut/iioRD7zghtLBr9Zeu8qGlWp+ANsT0UvQBRNkEPJjCt5mcuS6stuokQ/5IZ21QNK0Bmdzd9ANS6DMchS1eGi4YrZUaHcjII9Xf4xIHrGpRfo7ukLS2tdb4ANv0RcGRYGev7lbnom4THaSFIJGjF9SmlAvqEZuIQD5dk/c=
  app: intense-ravine-69222
  on:
    repo: bostons-elixir-women/lightning-talks
